application:
  name: demo

spring:
    profiles:
      active: dev
---
#server.context-path=/luoxiang
#luoxiang.name="\u7F57\u6E58"
#name=123
server:
  port: 8080
#seed=${random.value}
mybatis:
    typeAliasesPackage: com.xxx.firstboot.domain
    mapperLocations: classpath:mapper/*.xml
#debug=true
---
spring:
    profiles: dev
    application:
        name: ${application.name}-dev
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
   datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.2.180:3306/test?zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=utf-8
        username: root
        password: root
    redis:
            database: 0  # Redis数据库索引（默认为0）
            host: 192.168.2.180  # Redis服务器地址
            port: 6379 # Redis服务器连接端口
            password:    # Redis服务器连接密码（默认为空）
            pool:
                 max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
                 max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
                 max-idle: 8 # 连接池中的最大空闲连接
                 min-idle: 0 # 连接池中的最小空闲连接
            timeout: 30000  #连接超时时间（毫秒）
---